### ISSUE TITLE
Broken demo at codepen

### ISSUE THREAD

**Issue by firminochangani** [VitorLuizC/vue-data-tablee#14]
Hi @VitorLuizC, I wanted to see vue-data-tablee in action but unfortunately the demo on CodePen is broken. 
![screen shot 2018-09-27 at 4 51 40 pm](https://user-images.githubusercontent.com/1679333/46158389-a6c9b800-c275-11e8-88e3-bfd0bef88766.png)

**Comment by VitorLuizC** [comment]
Thank you for notifying me.

I've fixed it by replacing `RawGit` links to [`unpkg`](https://unpkg.com/) ones. `RawGit` seems to be using wrong mime types.
