### ISSUE TITLE
Define column style

### ISSUE THREAD

**Issue by Geminii** [VitorLuizC/vue-data-tablee#7]
Hi guys !
Do you plan to consider the following column style properties : 
- width
- hidden
- tdClass
- thClass 

I need to specify it into column property but not in custom template. That's a lot for your work ;)

**Comment by VitorLuizC** [comment]
That would be a nice addition!

**Comment by VitorLuizC** [comment]
I had to change `tdClass` to `contentClass` and `thClass` to `headerClass`, is this a problem?
I know some stuff keep VueGoodTable compatibility, but should this one keep it too?

**Comment by VitorLuizC** [comment]
I've published this over version `0.12.0`. And now we have docs, you can see new col properties on README O/

https://github.com/VitorLuizC/vue-data-tablee/commit/a3c939bd7538bfc6b305c3b8fa3e15e71d6f29e9
